name: Remote Dispatch Action Initiator

"on":
  pull_request: {}
  push:
    branches:
      - main
      - release/**
  workflow_dispatch: {}

env:
  DEBUG: 1
  GH_TOKEN: ${{ github.token }}

jobs:
  tx:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '{
            "event_type": "public-pr-opened",
            "client_payload": {
              "ref": "${{ github.ref }}"
            }
          }' tr -d $'\n' | tr -s ' ' \
          gh api \
            --input - \
            /repos/Scimia/Scimia-Private/dispatches
