name: Remote Dispatch Action Initiator

"on":
  pull_request: {}
  push:
    branches:
      - main
      - release/**
  workflow_dispatch: {}

env:
  DEBUG: 1
  # GH_TOKEN: ${{ github.token }}
  GH_TOKEN: ${{ secrets.SCIMIA_BOT_GITHUB_TOKEN }}

jobs:
  tx:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x

          echo '{"event_type":"test","client_payload":{"event":${{ toJSON(github.event) }}}}' \
            | gh api repos/Scimia/Scimia-Private/dispatches --input -
