name: Remote Dispatch Action Initiator

"on":
  pull_request: {}
  push:
    branches:
      - main
      - release/**
  workflow_dispatch: {}

env:
  DEBUG: 1
  GH_TOKEN: ${{ github.token }}

jobs:
  tx:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          payload="$(
            echo '{
              "event_type": "public-pr-opened",
              "client_payload": {
                "event": "${{ github.event }}"
              }
            }' | tr -d $'\n' | tr -s ' '
          )"

          echo "$payload" | gh api --input - \
            /repos/Scimia/Scimia-Private/dispatches
