name: Remote Dispatch Action Initiator

"on":
  pull_request: {}
  push:
    branches:
      - main
      - release/**
  workflow_dispatch: {}

env:
  DEBUG: 1
  GH_TOKEN: ${{ github.token }}

jobs:
  tx:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          payload="$(
            echo '{
              "event_type": "transit",
              "client_payload": {}
            }' | tr -d $'\n' | tr -s ' '
          )"

          echo '{"event_type":"test","client_playload":{}}' \
            | gh api repos/Scimia/Scimia-Private/dispatches --input -
