---

name: Workflow

on:
  workflow_dispatch
  
jobs:
  job:
    name: Job One
    runs-on: ubuntu-latest
    steps:
      - name: step one
        env:
          GITHUB_TOKEN: ${{ secrets.SCIMIA_BOT_GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          git clone https://github.com/Scimia/Scimia-Private.git
          git clone git@github.com:Scimia/Scimia-Private.git
