---

name: Workflow

on:
  workflow_dispatch
  
jobs:
  job:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    name: Job One
    runs-on: ubuntu-latest
    steps:
      - name: step one
        env:
          GITHUB_TOKEN: ${{ secrets.SCIMIA_BOT_GITHUB_TOKEN }}
          DEBUG: 1
        run: |
          set -x
          gh auth setup-git
          git clone https://github.com/Scimia/Scimia-Private.git one
          git clone git@github.com:Scimia/Scimia-Private.git two
